### ISSUE TITLE
feat/theme-color

### ISSUE THREAD

**Issue by Takahir-O** [recursion-teamgreen/git-workshop#26]
## 概要
現在白背景であまりかっこよくないので、全体の配色を考えたい

### 提案
カフェなので暖色系がいいかなと思ってます

## タスク
1. 背景色の変更
2. 文字色など変更

**Comment by Amnis333** [comment]
単色だとちょっとダサいので、グラデーションを付けるか、画像を背景にしようと思います。
フッターと被らない色の方がよさそうですかね。

**Comment by TakaToshi0801** [comment]
了解しました。
